services:
  jupyter:
    build: .
    container_name: jupyter-spark
    ports:
      - "8888:8888"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - RAWG_API_KEY=${RAWG_API_KEY}
    volumes:
      - ./notebooks:/home/jovyan/work